# Generated by Django 3.2.24 on 2024-03-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('tax', models.CharField(max_length=100)),
                ('discount', models.CharField(default=0, max_length=100, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel')),
                ('purchasebill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.purchasebill')),
            ],
        ),
    ]
