# Generated by Django 4.2.6 on 2024-05-24 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0011_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 24)),
        ),
    ]
