# Generated by Django 4.2.6 on 2024-05-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0012_salesinvoice_is_used_alter_history_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='is_used',
        ),
    ]
