# Generated by Django 4.2.6 on 2024-05-27 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0013_remove_salesinvoice_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 27)),
        ),
    ]
